package com.urlshortener.redirectshorturl.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;

@Data
@NoArgsConstructor
@AllArgsConstructor
// TODO: Pull this from the config file
@DynamoDBTable(tableName = "dev-url-shortener-short-urls")
public class ShortenedUrlInformation {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "LongUrl")
    private String longUrl;

    @DynamoDBAttribute(attributeName = "ShortUrl")
    @NotEmpty(message = "{shortUrl.notEmpty}")
    private String shortUrl;

}
